AI_CONFIG_BASENAME: .ai
configDirs:
  - $XDG_BIN_HOME
  - $XDG_CONFIG_HOME
  - $HOME
brainDir: ${XDG_DATA_HOME}/brain
agentDirs:
  - $XDG_BIN_HOME/../lib
  - ${XDG_DATA_HOME}/agent
promptDirs:
  - ${XDG_DATA_HOME}/prompt
chatsDir: ${XDG_DATA_HOME}/log/chats
inputsDir: ${XDG_DATA_HOME}/log/inputs
