AI_CONFIG_BASENAME: .ai
configDirs:
  - $XDG_BIN_HOME
  - $XDG_CONFIG_HOME
  - $HOME
brainDir: ${XDG_DATA_HOME}/brain
agentDirs:
  - ${XDG_DATA_HOME}/agent
  - $PWD
promptDirs:
  - ${XDG_DATA_HOME}/prompt
